FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY BinanceTimescaleDB.py .
COPY continuous_loader.py .

CMD ["python", "continuous_loader.py"]
